feat: fetch binary release of mdbook
Signed-off-by: Mateusz Urbanek <mateusz.urbanek.98@gmail.com>

diff --git a/.github/workflows/docs.yaml b/.github/workflows/docs.yaml
--- a/.github/workflows/docs.yaml
+++ b/.github/workflows/docs.yaml
@@ -30,14 +30,27 @@ jobs:
   build:
     runs-on: ubuntu-latest
     env:
-      MDBOOK_VERSION: 0.4.44
+      MDBOOK_VERSION: 0.4.45
     steps:
       - uses: actions/checkout@v4
       - name: Install mdBook
         run: |
-          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
-          rustup update
-          cargo install --version ${MDBOOK_VERSION} mdbook
+          set -e
+
+          # Download and install
+          URL="https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
+          echo "Downloading: $URL"
+          curl -L "$URL" -o mdbook.tar.gz
+
+          tar -xzf mdbook.tar.gz
+          chmod +x mdbook
+          sudo mv mdbook /usr/local/bin/
+
+          # Clean up
+          rm -f mdbook.tar.gz
+
+          echo "MDBook v$LATEST_VERSION installed successfully!"
+          mdbook --version
       - name: Setup Pages
         id: pages
         uses: actions/configure-pages@v5
